// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ColorProvider } from "./utils/ColorContext"; // Correct import path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RateMate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <ColorProvider>
          <Navbar />
          {children}
        </ColorProvider>
      </body>
    </html>
  );
}
